name: neo_bank
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  animate_do: ^3.1.2
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  flutter_tilt: ^2.2.1
  go_router: ^13.0.1
  google_fonts: ^6.1.0
  iconsax: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  assets:
    - assets/
    - assets/svgs/
    - assets/images/

  fonts:
    - family: ClashGrotesk
      fonts:
        - asset: assets/fonts/ClashGrotesk.ttf

  uses-material-design: true
